sudo: required
language: node_js
node_js:
  - "6"
  - "6.1"
cache:
  yarn: true
  directories:
    - bower_components
    - node_modules
branches:
  only:
    - master
    - /^greenkeeper/.*$/
install:
  - npm install -g npm@latest
  - npm install -g yarn bower
before_script:
  - npm prune
script:
  - chmod a+x build.sh && ./build.sh
